### ISSUE TITLE
Flagging Feature

### ISSUE THREAD

**Issue by Quinn-Donnelly** [revaturelabs/1808-cal-v2-meta#11]
ISSUE KEY: [CAL-154]

user should be able to click on the trainee name to toggle between red, green, and no flag - user should be able to persist flag status with a comment (this will need to be set up to be reusable for other pages)

[CAL-154]: https://revaturetraining.atlassian.net/browse/CAL-154

**Comment by Quinn-Donnelly** [comment]
Sprint 559

The flag appears and changes properly but the on click event is not triggered when clicking the flag you have to click off to the left. This should be changes. Also on hover the note is not appearing there is no way to see the note once saved.

**Comment by FrDKO** [comment]
@Quinn-Donnelly i have a question about this, maybe you can answer it on here:

Basically, the issue states that by design, we want the user to be able to click on the trainee's name to create a flag. Is that explicit? Seeing as its difficult for a user to inherently know that they have to click on the trainee's name. If we have a better implementation, is it alright if we use it?

**Comment by Quinn-Donnelly** [comment]
@FrDKO No that is the current functionality of Caliber and the original designer documented the features they were then copied over by all means if you can implement more intuitive designs please due so.

**Comment by FrDKO** [comment]
@Quinn-Donnelly 

We were getting Cors issues during our showing you the application. It works fine, if you want to come see it running.

**Comment by Quinn-Donnelly** [comment]
Sprint 587

Feature is approved and has passed UAT. Merged into dev.
